version: '2'
services:
  tooling_frontend:
    container_name: tooling
    build:
      context: ./
    volumes:
      - tooling_frontend:/var/www/html:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - mysql
  mysql:
        image: mysql:8.0
        container_name: mysqlserverhost
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_DATABASE='${MYSQL_DBNAME}'
          - MYSQL_USER='${MYSQL_USER}'
          - MYSQL_PASSWORD='${MYSQL_PASS}'
          - MYSQL_ROOT_PASSWORD='1'

        ports:
          - "3306:3306"
volumes:
  tooling_frontend:
  mysql:
