version: '3'

services: 
  tooling_frontend:
      build: .
      image: stlng/tooling-${BRANCH_NAME}:${BUILD_NUMBER}
      container_name: tooling
      ports:
        - "5000:80"
      volumes:
        - tooling_frontend:/var/www
      networks:
        - tooling_app_network
      links:
        - db
  db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always 
      environment:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: '${MYSQL_DBNAME}'
          MYSQL_USER: '${MYSQL_USER}'
          MYSQL_PASSWORD: '${MYSQL_PASS}'
      ports: 
          - 3306:3306
      volumes:
          - db:/var/lib/mysql
      networks:
          - tooling_app_network
volumes:
  tooling_frontend:
  db:
networks:
  tooling_app_network : {}